/* This Java source file was generated by the Gradle 'init' task. */
package de.pottgames.tuningfork;

/**
 * A test class.
 *
 * @author Matthias
 *
 */
public class Library {

    /**
     * A test method.
     *
     * @return always returns true
     */
    public boolean someLibraryMethod() {
        return true;
    }

}
