[package]
name = "decoders_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
jni = "0.20.0"
itertools = "0.10.5"

[features]
debug_assertions = []

[profile.release]
lto = true
incremental = false
codegen-units = 1

[lib]
crate_type = ["cdylib", "lib"]
name = "decoders_rs64"

