package de.pottgames.tuningfork.decoder;

import com.badlogic.gdx.utils.IntMap;

public enum WavAudioFormat {
    WAVE_FORMAT_UNKNOWN(0x0000, "WAVE_FORMAT_UNKNOWN"),
    WAVE_FORMAT_PCM(0x0001, "WAVE_FORMAT_PCM"),
    WAVE_FORMAT_ADPCM(0x0002, "WAVE_FORMAT_ADPCM"),
    WAVE_FORMAT_IEEE_FLOAT(0x0003, "WAVE_FORMAT_IEEE_FLOAT"),
    WAVE_FORMAT_VSELP(0x0004, "WAVE_FORMAT_VSELP"),
    WAVE_FORMAT_IBM_CVSD(0x0005, "WAVE_FORMAT_IBM_CVSD"),
    WAVE_FORMAT_ALAW(0x0006, "WAVE_FORMAT_ALAW"),
    WAVE_FORMAT_MULAW(0x0007, "WAVE_FORMAT_MULAW"),
    WAVE_FORMAT_OKI_ADPCM(0x0010, "WAVE_FORMAT_OKI_ADPCM"),
    WAVE_FORMAT_DVI_ADPCM(0x0011, "WAVE_FORMAT_DVI_ADPCM"),
    WAVE_FORMAT_MEDIASPACE_ADPCM(0x0012, "WAVE_FORMAT_MEDIASPACE_ADPCM"),
    WAVE_FORMAT_SIERRA_ADPCM(0x0013, "WAVE_FORMAT_SIERRA_ADPCM"),
    WAVE_FORMAT_G723_ADPCM(0x0014, "WAVE_FORMAT_G723_ADPCM"),
    WAVE_FORMAT_DIGISTD(0x0015, "WAVE_FORMAT_DIGISTD"),
    WAVE_FORMAT_DIGIFIX(0x0016, "WAVE_FORMAT_DIGIFIX"),
    WAVE_FORMAT_DIALOGIC_OKI_ADPCM(0x0017, "WAVE_FORMAT_DIALOGIC_OKI_ADPCM"),
    WAVE_FORMAT_MEDIAVISION_ADPCM(0x0018, "WAVE_FORMAT_MEDIAVISION_ADPCM"),
    WAVE_FORMAT_CU_CODEC(0x0019, "WAVE_FORMAT_CU_CODEC"),
    WAVE_FORMAT_YAMAHA_ADPCM(0x0020, "WAVE_FORMAT_YAMAHA_ADPCM"),
    WAVE_FORMAT_SONARC(0x0021, "WAVE_FORMAT_SONARC"),
    WAVE_FORMAT_DSPGROUP_TRUESPEECH(0x0022, "WAVE_FORMAT_DSPGROUP_TRUESPEECH"),
    WAVE_FORMAT_ECHOSC1(0x0023, "WAVE_FORMAT_ECHOSC1"),
    WAVE_FORMAT_AUDIOFILE_AF36(0x0024, "WAVE_FORMAT_AUDIOFILE_AF36"),
    WAVE_FORMAT_APTX(0x0025, "WAVE_FORMAT_APTX"),
    WAVE_FORMAT_AUDIOFILE_AF10(0x0026, "WAVE_FORMAT_AUDIOFILE_AF10"),
    WAVE_FORMAT_PROSODY_1612(0x0027, "WAVE_FORMAT_PROSODY_1612"),
    WAVE_FORMAT_LRC(0x0028, "WAVE_FORMAT_LRC"),
    WAVE_FORMAT_DOLBY_AC2(0x0030, "WAVE_FORMAT_DOLBY_AC2"),
    WAVE_FORMAT_GSM610(0x0031, "WAVE_FORMAT_GSM610"),
    WAVE_FORMAT_MSNAUDIO(0x0032, "WAVE_FORMAT_MSNAUDIO"),
    WAVE_FORMAT_ANTEX_ADPCME(0x0033, "WAVE_FORMAT_ANTEX_ADPCME"),
    WAVE_FORMAT_CONTROL_RES_VQLPC(0x0034, "WAVE_FORMAT_CONTROL_RES_VQLPC"),
    WAVE_FORMAT_DIGIREAL(0x0035, "WAVE_FORMAT_DIGIREAL"),
    WAVE_FORMAT_DIGIADPCM(0x0036, "WAVE_FORMAT_DIGIADPCM"),
    WAVE_FORMAT_CONTROL_RES_CR10(0x0037, "WAVE_FORMAT_CONTROL_RES_CR10"),
    WAVE_FORMAT_NMS_VBXADPCM(0x0038, "WAVE_FORMAT_NMS_VBXADPCM"),
    WAVE_FORMAT_ROLAND_RDAC(0x0039, "WAVE_FORMAT_ROLAND_RDAC"),
    WAVE_FORMAT_ECHOSC3(0x003a, "WAVE_FORMAT_ECHOSC3"),
    WAVE_FORMAT_ROCKWELL_ADPCM(0x003b, "WAVE_FORMAT_ROCKWELL_ADPCM"),
    WAVE_FORMAT_ROCKWELL_DIGITALK(0x003c, "WAVE_FORMAT_ROCKWELL_DIGITALK"),
    WAVE_FORMAT_XEBEC(0x003d, "WAVE_FORMAT_XEBEC"),
    WAVE_FORMAT_G721_ADPCM(0x0040, "WAVE_FORMAT_G721_ADPCM"),
    WAVE_FORMAT_G728_CELP(0x0041, "WAVE_FORMAT_G728_CELP"),
    WAVE_FORMAT_MSG723(0x0042, "WAVE_FORMAT_MSG723"),
    WAVE_FORMAT_MPEG(0x0050, "WAVE_FORMAT_MPEG"),
    WAVE_FORMAT_RT24(0x0052, "WAVE_FORMAT_RT24"),
    WAVE_FORMAT_PAC(0x0053, "WAVE_FORMAT_PAC"),
    WAVE_FORMAT_MPEGLAYER3(0x0055, "WAVE_FORMAT_MPEGLAYER3"),
    WAVE_FORMAT_LUCENT_G723(0x0059, "WAVE_FORMAT_LUCENT_G723"),
    WAVE_FORMAT_CIRRUS(0x0060, "WAVE_FORMAT_CIRRUS"),
    WAVE_FORMAT_ESPCM(0x0061, "WAVE_FORMAT_ESPCM"),
    WAVE_FORMAT_VOXWARE(0x0062, "WAVE_FORMAT_VOXWARE"),
    WAVE_FORMAT_CANOPUS_ATRAC(0x0063, "WAVE_FORMAT_CANOPUS_ATRAC"),
    WAVE_FORMAT_G726_ADPCM(0x0064, "WAVE_FORMAT_G726_ADPCM"),
    WAVE_FORMAT_G722_ADPCM(0x0065, "WAVE_FORMAT_G722_ADPCM"),
    WAVE_FORMAT_DSAT(0x0066, "WAVE_FORMAT_DSAT"),
    WAVE_FORMAT_DSAT_DISPLAY(0x0067, "WAVE_FORMAT_DSAT_DISPLAY"),
    WAVE_FORMAT_VOXWARE_BYTE_ALIGNED(0x0069, "WAVE_FORMAT_VOXWARE_BYTE_ALIGNED"),
    WAVE_FORMAT_VOXWARE_AC8(0x0070, "WAVE_FORMAT_VOXWARE_AC8"),
    WAVE_FORMAT_VOXWARE_AC10(0x0071, "WAVE_FORMAT_VOXWARE_AC10"),
    WAVE_FORMAT_VOXWARE_AC16(0x0072, "WAVE_FORMAT_VOXWARE_AC16"),
    WAVE_FORMAT_VOXWARE_AC20(0x0073, "WAVE_FORMAT_VOXWARE_AC20"),
    WAVE_FORMAT_VOXWARE_RT24(0x0074, "WAVE_FORMAT_VOXWARE_RT24"),
    WAVE_FORMAT_VOXWARE_RT29(0x0075, "WAVE_FORMAT_VOXWARE_RT29"),
    WAVE_FORMAT_VOXWARE_RT29HW(0x0076, "WAVE_FORMAT_VOXWARE_RT29HW"),
    WAVE_FORMAT_VOXWARE_VR12(0x0077, "WAVE_FORMAT_VOXWARE_VR12"),
    WAVE_FORMAT_VOXWARE_VR18(0x0078, "WAVE_FORMAT_VOXWARE_VR18"),
    WAVE_FORMAT_VOXWARE_TQ40(0x0079, "WAVE_FORMAT_VOXWARE_TQ40"),
    WAVE_FORMAT_SOFTSOUND(0x0080, "WAVE_FORMAT_SOFTSOUND"),
    WAVE_FORMAT_VOXWARE_TQ60(0x0081, "WAVE_FORMAT_VOXWARE_TQ60"),
    WAVE_FORMAT_MSRT24(0x0082, "WAVE_FORMAT_MSRT24"),
    WAVE_FORMAT_G729A(0x0083, "WAVE_FORMAT_G729A"),
    WAVE_FORMAT_MVI_MV12(0x0084, "WAVE_FORMAT_MVI_MV12"),
    WAVE_FORMAT_DF_G726(0x0085, "WAVE_FORMAT_DF_G726"),
    WAVE_FORMAT_DF_GSM610(0x0086, "WAVE_FORMAT_DF_GSM610"),
    WAVE_FORMAT_ISIAUDIO(0x0088, "WAVE_FORMAT_ISIAUDIO"),
    WAVE_FORMAT_ONLIVE(0x0089, "WAVE_FORMAT_ONLIVE"),
    WAVE_FORMAT_SBC24(0x0091, "WAVE_FORMAT_SBC24"),
    WAVE_FORMAT_DOLBY_AC3_SPDIF(0x0092, "WAVE_FORMAT_DOLBY_AC3_SPDIF"),
    WAVE_FORMAT_ZYXEL_ADPCM(0x0097, "WAVE_FORMAT_ZYXEL_ADPCM"),
    WAVE_FORMAT_PHILIPS_LPCBB(0x0098, "WAVE_FORMAT_PHILIPS_LPCBB"),
    WAVE_FORMAT_PACKED(0x0099, "WAVE_FORMAT_PACKED"),
    WAVE_FORMAT_RHETOREX_ADPCM(0x0100, "WAVE_FORMAT_RHETOREX_ADPCM"),
    WAVE_FORMAT_IRAT(0x0101, "WAVE_FORMAT_IRAT"),
    WAVE_FORMAT_VIVO_G723(0x0111, "WAVE_FORMAT_VIVO_G723"),
    WAVE_FORMAT_VIVO_SIREN(0x0112, "WAVE_FORMAT_VIVO_SIREN"),
    WAVE_FORMAT_DIGITAL_G723(0x0123, "WAVE_FORMAT_DIGITAL_G723"),
    WAVE_FORMAT_CREATIVE_ADPCM(0x0200, "WAVE_FORMAT_CREATIVE_ADPCM"),
    WAVE_FORMAT_CREATIVE_FASTSPEECH8(0x0202, "WAVE_FORMAT_CREATIVE_FASTSPEECH8"),
    WAVE_FORMAT_CREATIVE_FASTSPEECH10(0x0203, "WAVE_FORMAT_ CREATIVE_FASTSPEECH10"),
    WAVE_FORMAT_QUARTERDECK(0x0220, "WAVE_FORMAT_QUARTERDECK"),
    WAVE_FORMAT_FM_TOWNS_SND(0x0300, "WAVE_FORMAT_FM_TOWNS_SND"),
    WAVE_FORMAT_BTV_DIGITAL(0x0400, "WAVE_FORMAT_BTV_DIGITAL"),
    WAVE_FORMAT_VME_VMPCM(0x0680, "WAVE_FORMAT_VME_VMPCM"),
    WAVE_FORMAT_OLIGSM(0x1000, "WAVE_FORMAT_OLIGSM"),
    WAVE_FORMAT_OLIADPCM(0x1001, "WAVE_FORMAT_OLIADPCM"),
    WAVE_FORMAT_OLICELP(0x1002, "WAVE_FORMAT_OLICELP"),
    WAVE_FORMAT_OLISBC(0x1003, "WAVE_FORMAT_OLISBC"),
    WAVE_FORMAT_OLIOPR(0x1004, "WAVE_FORMAT_OLIOPR"),
    WAVE_FORMAT_LH_CODEC(0x1100, "WAVE_FORMAT_LH_CODEC"),
    WAVE_FORMAT_NORRIS(0x1400, "WAVE_FORMAT_NORRIS"),
    WAVE_FORMAT_ISIAUDIO_(0x1401, "WAVE_FORMAT_ISIAUDIO"),
    WAVE_FORMAT_SOUNDSPACE_MUSICOMPRESS(0x1500, "WAVE_FORMAT_SOUNDSPACE_MUSICOMPRESS"),
    WAVE_FORMAT_DVM(0x2000, "WAVE_FORMAT_DVM"),
    WAVE_FORMAT_EXTENSIBLE(0xfffe, "WAVE_FORMAT_EXTENSIBLE");


    private static final IntMap<WavAudioFormat> MAP = new IntMap<>();
    private final int                           regNumber;
    private final String                        wFormatTagId;

    static {
        for (final WavAudioFormat format : WavAudioFormat.values()) {
            WavAudioFormat.MAP.put(format.regNumber, format);
        }
    }


    WavAudioFormat(int regNumber, String wFormatTagId) {
        this.regNumber = regNumber;
        this.wFormatTagId = wFormatTagId;
    }


    public int getRegNumber() {
        return regNumber;
    }


    public String getWFormatTagId() {
        return wFormatTagId;
    }


    public static WavAudioFormat getByRegNumber(int regNumber) {
        return WavAudioFormat.MAP.get(regNumber);
    }

}
